default: &default
  project: "app"
  host: "localhost"
  protocol: "http"

development:
  <<: *default
  env: "development"
  port: "3300"
  apiUrl: "http://localhost:3001/api/v1"

production:
  <<: *default
  env: "production"
  host: "app.com"
  protocol: "https"

  apiUrl: "http://app.com/api/v1"
  assetOrigin: "http://wavepuzzle.com"
